from django.urls import path
from .views import (
    AddToCartView,
    CancelOrderView,
    CartCountView,
    ClearCartView,
    CompletePaymentView,
    CartView,
    CreateOrderView,
    OrderDetailView,
    OrderListView,
    OrderStatusUpdateView,
    PaymentIntentView,
    RemoveCartItemView,
    SimulatePaymentView,
    UpdateCartItemView,
    stripe_webhook,
)

urlpatterns = [
    path("cart/", CartView.as_view(), name="cart"),
    path("cart/add/", AddToCartView.as_view(), name="cart-add"),
    path("cart/count/", CartCountView.as_view(), name="cart-count"),
    path("cart/items/<int:pk>/", UpdateCartItemView.as_view(), name="cart-item-update"),
    path("cart/items/<int:pk>/remove/", RemoveCartItemView.as_view(), name="cart-item-remove"),
    path("cart/clear/", ClearCartView.as_view(), name="cart-clear"),
    path("", OrderListView.as_view(), name="order-list"),
    path("create/", CreateOrderView.as_view(), name="order-create"),
    path("<int:pk>/", OrderDetailView.as_view(), name="order-detail"),
    path("<int:pk>/cancel/", CancelOrderView.as_view(), name="order-cancel"),
    path("<int:pk>/payment-intent/", PaymentIntentView.as_view(), name="payment-intent"),
    path("<int:pk>/complete-payment/", CompletePaymentView.as_view(), name="complete-payment"),
    path("<int:pk>/status/", OrderStatusUpdateView.as_view(), name="order-status-update"),
    path("<int:pk>/simulate-payment/", SimulatePaymentView.as_view(), name="simulate-payment"),
    path("webhook/stripe/", stripe_webhook, name="stripe-webhook"),
]
