# Generated by Django 5.2.15 on 2026-06-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_available'], name='menu_menuit_is_avai_3a30d9_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'is_available'], name='menu_menuit_categor_ed897a_idx'),
        ),
    ]
