# Generated by Django 5.2.15 on 2026-06-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_menu_menuit_is_avai_3a30d9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='image URL'),
        ),
    ]
