# Generated by Django 5.2.15 on 2026-06-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_profile_address_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_district',
            field=models.CharField(blank=True, max_length=100, verbose_name='district'),
        ),
    ]
