# Generated by Django 5.2.15 on 2026-06-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_address_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_building',
            field=models.CharField(max_length=50, verbose_name='building'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_city',
            field=models.CharField(max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_district',
            field=models.CharField(max_length=100, verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_flat',
            field=models.CharField(max_length=20, verbose_name='flat'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_floor',
            field=models.CharField(max_length=20, verbose_name='floor'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_street',
            field=models.TextField(verbose_name='street'),
        ),
    ]
